const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const AccessSchema = new Schema({
    _id: {
        // autogenerated by mongo, don't use for usual id
        type: ObjectId,
        required: true,
    },
    uuid: {
        type: String,
        required: true,
        unique: true,
    },
    role: {
        type: String,
        required: true,
    },
    accessCode: {
        type: String,
        required: true,
    },
});

module.exports = Access = mongoose.model("accesses", AccessSchema);
