const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const AccessSchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    role: {
        type: String, // role associated with this access (e.g., admin, novice)
        required: true,
    },
    accessCode: {
        type: String, // code or token used to grant access
        required: true,
    },
});

module.exports = Access = mongoose.model("accesses", AccessSchema);
