const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const AnnouncementSchema = new Schema({
    _id: { 
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    title: {
        type: String, // optional title
    },
    type: {
        type: String, // general label for announcement
        required: true,
        enum: ["event", "classes", "other"],
    },
    status: {
        type: String, // scheduled if pending, posted if showing to users
        enum: ["scheduled", "posted"],
        required: true,
    },
    description: {
        type: String, // detailed description of the announcement
        required: true,
    },
    createdBy: {
        type: String, // uuid of the user who created the announcement
        ref: "User",
        required: true,
    },
    dateCreated: {
        type: Date, // date the announcement was created
        required: true,
    },
    lastUpdatedBy: {
        type: String, // uuid of the user who last updated the announcement
        ref: "User",
        required: true,
    },
    dateLastUpdated: {
        type: Date, // date the announcement was last updated
        required: true,
    },
});

module.exports = Announcement = mongoose.model(
    "announcements",
    AnnouncementSchema
);
