const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const AnnouncementSchema = new Schema({
    _id: { // autogenerated by mongo, don't use for usual id
        type: ObjectId,
        required: true,
    },
    uuid: {
        type: String,
        required: true,
        unique: true,
    },
    title: {
        type: String, // optional title
    },
    type: {
        type: String, // general label for announcement
        required: true,
        enum: ["event", "classes", "other"],
    },
    status: {
        type: String, // scheduled if pending, posted if showing to users
        enum: ["scheduled", "posted"],
        required: true,
    },
    description: {
        type: String,
        required: true,
    },
    createdBy: {
        type: String,
        ref: "User",
        required: true,
    },
    dateCreated: {
        type: Date,
        required: true,
    },
    lastUpdatedBy: {
        type: String,
        ref: "User",
        required: true,
    },
    dateLastUpdated: {
        type: Date,
        required: true,
    },
});

module.exports = Announcement = mongoose.model(
    "announcements",
    AnnouncementSchema
);
