const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const CategorySchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    name: {
        type: String, // full name of the category (ex. Filament)
        required: true,
    },
    defaultIssues: [{ type: String, required: true }], // list of common issues for this category
    properties: [
        {
            type: String,
            enum: ["temperature"], // list of special properties relevant to this category (hard coded)
        },
    ],
    color: { type: String, required: true }, // color associated with this category
});

module.exports = Category = mongoose.model("categories", CategorySchema);
