const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const EquipmentSchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    name: { type: String, required: true }, // full name of the equipment
    routePath: { type: String, required: true }, // web page path for the equipment
    headline: { type: String }, // short headline or tagline for the equipment
    ipUrl: { type: String }, // IP address or URL to access the equipment
    cameraUrl: { type: String }, // URL to access a camera feed for the equipment
    remotePrintAvailable: { // indicates if the equipment is available for remote printing
        type: Boolean,
        required: true,
    },
    categoryId: { 
        type: String, // uuid of the category this equipment belongs to
        required: true,
        ref: "Category",
    },
    status: {
        type: String,
        enum: ["available", "paused", "busy", "error", "offline"],
        required: true,
    },
    /*
        available - printer is working as intended and no one is printing with it
        paused - printer is working as intended but it's paused currently
        busy - printer is working as intended and it is printing something
        error - printer has a reported issue or is being fixed - won't allow prints on this
        offline - printer is completely offline (can't find in the network) - won't allow prints on this
    */
    description: {
        type: String,
        required: true,
    },
});

module.exports = Equipment = mongoose.model("equipment", EquipmentSchema);
