const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const IssueSchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    equipmentId: {
        type: String, // uuid of the equipment this issue is associated with
        ref: "Equipment",
        required: true,
    },
    status: {
        type: String, // current status of the issue
        enum: ["open", "in-progress", "completed"],
        required: true,
    },
    initialDescription: {
        type: String, // brief description of the issue when first reported
    },
    description: {
        type: String, // detailed description of the issue
        required: true,
    },
    createdBy: {
        type: String, // uuid of the user who created the issue
        ref: "User",
        required: true,
    },
    dateCreated: {
        type: Date, // date the issue was created
        required: true,
    },
    assignedTo: [
        {
            type: String, // uuid of the user(s) assigned to address the issue
            ref: "User",
        },
    ],
});

IssueSchema.pre("save", function (next) {
    this.status = this.status.toLowerCase();
    next();
});

module.exports = Issue = mongoose.model("issues", IssueSchema);
