const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const JobSchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    equipmentId: {
        type: String, // uuid of the equipment this job is associated with
        ref: "Equipment",
        required: true,
    },
    userId: {
        type: String, // uuid of the user who created the job
        ref: "User",
        required: true,
    },
    gcodeFileName: { type: String, required: true }, // name of the G-code file to be printed
    status: {
        type: String, // current status of the job
        enum: ["queued", "ready", "printing", "completed", "failed"],
        required: true,
        lowercase: true,
    },
    lastPrompt: {
        type: String,
        enum: [
            "NONE",
            "SUCCESS_CHECK",
            "REPRINT_CHECK",
            "FAILURE_REASON",
            "BED_CLEAR_CHECK",
        ],
        default: "NONE",
    },
    
    order: { type: Number, required: true }, // order of the job in the queue for the equipment, only for jobs with status "queued"
    failureReason: { type: String, default: "" }, // if status is failed, this field can contain the reason
    filamentUsedGrams: { type: Number, default: 0 }, // estimated filament used in grams
    estimatedTimeSeconds: { type: Number, default: 0 }, // estimated print time in seconds
    createdAt: { type: Date, default: Date.now }, // date the job was created
    uploadedAt: { type: Date }, // date the G-code file was uploaded and job was marked ready
    finishedAt: { type: Date }, // date the print completed or failed

});

module.exports = Job = mongoose.model("jobs", JobSchema);
