const mongoose = require("mongoose");
const { Schema } = mongoose;
const { ObjectId } = Schema.Types;

const MaterialSchema = new Schema({
    _id: {
        type: ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    name: {
        type: String, // full name of the material (ex. Polylactic Acid)
        required: true,
    },
    shortName: {
        type: String, // short name or abbreviation of the material (ex. PLA)
        required: true,
    },
    categoryId: {
        type: String, // uuid of the category this material belongs to
        required: true,
        ref: "Category"
    },
    properties: {
        type: [{ type: String }], // list of properties or characteristics of the material
    },
    description: {
        type: String, // detailed description of the material
    },
    remotePrintAvailable: {
        type: Boolean, // indicates if the material is available for remote printing
        required: true,
    },
    remotePrintEquipmentIds: [{
        type: String, // list of equipment uuids with this material loaded and available for remote printing
        ref: "Equipment",
    }],
    temperatures: { // special temperatures for printing with this material (filament only)
        extruder: {
            firstLayer: { type: Number },
            otherLayers: { type: Number },
        },
        bed: {
            firstLayer: { type: Number },
            otherLayers: { type: Number },
        },
    },
});

MaterialSchema.pre("save", function (next) {
    this.name = this.name.charAt(0).toUpperCase() + this.name.slice(1);
    this.shortName = this.shortName.toUpperCase();
    next();
});

module.exports = Material = mongoose.model("materials", MaterialSchema);
