const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const { Schema } = mongoose;

const UserSchema = new Schema({
    _id: {
        type: Schema.Types.ObjectId, // autogenerated from mongodb, not used directly
        required: true,
    },
    uuid: {
        type: String, // autogenerated unique identifier, used in API calls
        required: true,
        unique: true,
    },
    firstName: {
        type: String, // first name of the user
        required: true,
    },
    lastName: {
        type: String, // last name of the user
        required: true,
    },
    email: {
        type: String, // email address of the user
        required: true,
        lowercase: true,
        unique: true,
    },
    password: {
        type: String, // hashed password of the user
        required: true,
        select: false,
    },
    access: {
        type: String, // access level of the user
        required: true,
        enum: ["novice", "proficient", "expert", "moderator", "admin"],
        lowercase: true,
        /* 
            novice = never taken rapid prototyping
            proficient = taken rapid prototyping and maybe a few projects
            expert = "superuser", allowed certain permissions
            moderator = has edit access to issues and other things
            admin = edit access to everything, including user roles
        */
    },
    status: {
        type: String, // current status of the user
        required: true,
        default: "undergraduate",
        lowercase: true,
        enum: ["undergraduate", "graduate", "faculty"],
        /*
            undergraduate - have a graduation date, when reached need to remove
            graduate - have graduation date, when reached need to remove
            faculty - never deleted unless manually
        */
    },
    graduationDate: {
        type: Date, // if student, date of graduation
    },
    departments: {
        type: [String], // if faculty, department, if student, major(s) and minors
    },
});

UserSchema.pre("save", async function (next) {
    if (!this.isModified("password")) return next();
    const salt = await bcrypt.genSalt(10);
    this.password = await bcrypt.hash(this.password, salt);

    this.firstName =
        this.firstName.charAt(0).toUpperCase() + this.firstName.slice(1);
    this.lastName =
        this.lastName.charAt(0).toUpperCase() + this.lastName.slice(1);

    this.email = this.email.toLowerCase();
    this.access = this.access.toLowerCase();
    this.status = this.status.toLowerCase();

    next();
});

UserSchema.methods.comparePassword = async function (password) {
    return await bcrypt.compare(password, this.password);
};
UserSchema.methods.setPassword = async function (newPassword) {
    this.password = newPassword;
};

module.exports = User = mongoose.model("user", UserSchema);
